version: '3.4'

services:
  customers-service:
    container_name: bc3k-customers-services-vs
    image: bc3k/customers-services
    build:
      context: .
      dockerfile: BC3K.Customers.Service/Dockerfile
    ports:
      - "5001:5000"
    networks: 
      - services
    environment: 
      - ASPNETCORE_ENVIROIMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - IgnoreSslErrors=true
networks: 
  services: 
    external: 
      name: bc3k-devenv_default